#!/bin/bash

## This is simple script to run vacuum command at night, shoud be run under postgres user

source /etc/postgres_commands.cfg

echo "-------------------------------------------" >> $vacuum_log
echo "START $(date)" >> $vacuum_log
echo "-------------------------------------------" >> $vacuum_log

vacuumdb -v -d $db_name >> $vacuum_log 2>&1

echo "-------------------------------------------" >> $vacuum_log
echo "DONE $(date)" >> $vacuum_log
echo "-------------------------------------------" >> $vacuum_log
