#!/bin/bash

## This is simple script to run reindex command at night, shoud be run under postgres user

source /etc/postgres_commands.cfg

echo "-------------------------------------------" >> $reindex_log
echo "START $(date)" >> $reindex_log
echo "-------------------------------------------" >> $reindex_log

reindexdb $db_name >> $reindex_log 2>&1

echo "-------------------------------------------" >> $reindex_log
echo "DONE $(date)" >> $reindex_log
echo "-------------------------------------------" >> $reindex_log
