#!/bin/bash

## This is simple script to run vacuum full command at night, shoud be run under postgres user

source /etc/postgres_commands.cfg

echo "-------------------------------------------" >> $vacuum_full_log
echo "START $(date)" >> $vacuum_full_log
echo "-------------------------------------------" >> $vacuum_full_log

vacuumdb -f -v -d $db_name >> $vacuum_full_log 2>&1

echo "-------------------------------------------" >> $vacuum_full_log
echo "DONE $(date)" >> $vacuum_full_log
echo "-------------------------------------------" >> $vacuum_full_log
