#!/bin/bash

source /etc/postgres_commands.cfg

pg_dumpall -g --file=pg_backup_globals_`date +%d-%m-%Y_%H:%M:%S`.sql
for db_name in $db_names
do
	PGPASSWORD=$password pg_dump -h -Fc -d $db_name --file='pg_backup_'$db_name'_'`date +%d-%m-%Y_%H:%M:%S`'.dump'
done